create table p1 partition of t for values in (1 + 1);
create table p1 partition of t for values from (date '2020-01-01') to ('2021-01-01'::date);
create table p1 partition of t for values from (-1) to (+5);
create table p1 partition of t for values in ('a' || 'b', 3.5, true, null, 'x', now());
create table p1 partition of t for values from (minvalue, 1) to (maxvalue, 2);
create table p1 partition of t for values from (1) to (2 * 3);
alter table t attach partition p for values in (1 + 1);
alter table t alter column a add generated always as identity (sequence name s);
create table t (a int generated always as identity (sequence name public.s start 5 cache 2), b int generated by default as identity (sequence name "S"));
