-- Every clause of a column or table constraint

create table t (a int references p (id) match full);

create table t (a int, check (a > 0) no inherit);

create table t (a int, unique (a) include (b) with (fillfactor = 70) using index tablespace ts);

create table t (a int, b int, foreign key (a, b) references p on delete set null (b));

create table t (a int generated by default as identity (start with 10 increment by 5));

create table t (a int, primary key (a) deferrable initially deferred);

create table t (a int constraint nn not null);

alter table t add constraint u unique using index i;

alter table t add constraint c check (a > 0) not valid;

create table t (a int, exclude using gist (a with =) where (a > 0));

create table t (a text collate "C", b int default 1 check (b > 0));

create table t (a int references p on update cascade on delete restrict deferrable);

create table t (a int, exclude using gist (a with =));
