alter table t alter column a add generated by default as identity (start with 5 increment by 2 minvalue 1 maxvalue 1000 cache 10 cycle);
create table t (a integer generated always as identity (sequence name public.s start with 5 cache 2), b integer generated by default as identity);
create table t (very_long_column_name_one bigint generated always as identity (start with 1000 increment by 10 minvalue 1000 maxvalue 99999999 cache 20));
