/**
 * The libpg_query fields the AST builder doesn't read (see PgsqlPropertyCoverage.cs),
 * each with the reason. property-coverage.test.ts requires this list to match exactly.
 */

/** Safe to leave unread: the field means nothing the output doesn't already say. */
export const unused: Record<string, string> = {
    'ParseResult.Version': "libpg_query's version, not part of the SQL",
    'ColumnDef.IsLocal': 'always true from the parser',
    'NamedArgExpr.Argnumber': 'always -1 from the parser',
    'TypeName.Typemod': 'always -1 from the parser; the modifiers written are Typmods, which the builder reads',
    'Constraint.InitiallyValid': 'the opposite of SkipValidation (NOT VALID), which the builder reads',
    'MultiAssignRef.Colno': 'the position of the column in SET (a, b) = ..., which follows from the order',
    'PartitionBoundSpec.Strategy': 'follows from FOR VALUES IN / FROM ... TO / WITH (MODULUS ...), which the builder reads',
    'DeallocateStmt.Isall': 'DEALLOCATE ALL has no name, and a missing name prints as ALL',
    'DefineStmt.Oldstyle':
        'the old CREATE AGGREGATE syntax has no argument list and puts BASETYPE in the definition, which the builder prints',
};

/**
 * The raw parser never sets these: PostgreSQL fills them in during parse analysis or
 * execution, after the stage libpg_query runs. Checked by walking the parse trees of every
 * fixture and a corpus of statements meant to set them.
 */
export const unreachable: Record<string, string> = {
    'AlterOwnerStmt.Relation': 'the grammar never sets it; ALTER TABLE ... OWNER TO is an AlterTableCmd',
    'AlterPublicationStmt.ForAllTables': 'ALTER PUBLICATION has no FOR ALL TABLES form',
    'AlterSeqStmt.ForIdentity': 'set for the sequence behind an identity column, which PostgreSQL creates itself',
    'AlterTableCmd.Recurse': 'ONLY is RangeVar.Inh, which the builder reads',
    'BoolExpr.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'BooleanTest.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'CTECycleClause.CycleMarkCollation': 'a collation, filled in by parse analysis',
    'CTECycleClause.CycleMarkNeop': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'CTECycleClause.CycleMarkType': 'a type or type modifier, filled in by parse analysis',
    'CTECycleClause.CycleMarkTypmod': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'CallStmt.Funcexpr': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'CallStmt.Outargs': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'CaseExpr.Casecollid': 'a collation, filled in by parse analysis',
    'CaseExpr.Casetype': 'a type or type modifier, filled in by parse analysis',
    'CaseExpr.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'CaseWhen.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'CoalesceExpr.Coalescecollid': 'a collation, filled in by parse analysis',
    'CoalesceExpr.Coalescetype': 'a type or type modifier, filled in by parse analysis',
    'CoalesceExpr.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'ColumnDef.CollOid': 'a collation, filled in by parse analysis',
    'ColumnDef.CookedDefault': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'ColumnDef.Generated': 'GENERATED ... AS is parsed as a Constraint, which the builder reads',
    'ColumnDef.Identity': 'GENERATED ... AS IDENTITY is parsed as a Constraint, which the builder reads',
    'ColumnDef.IdentitySequence': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'ColumnDef.Inhcount': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'ColumnDef.IsFromType': 'set by analysis for CREATE TABLE ... OF type; the raw parser leaves it unset',
    'ColumnDef.IsNotNull': 'NOT NULL is parsed as a Constraint, which the builder reads',
    'ColumnDef.Storage': 'STORAGE is parsed into StorageName, which the builder reads',
    'CommonTableExpr.Ctecolcollations': 'a collation, filled in by parse analysis',
    'CommonTableExpr.Ctecolnames': 'filled in by analysis; the column names written are Aliascolnames, which the builder reads',
    'CommonTableExpr.Ctecoltypes': 'a type or type modifier, filled in by parse analysis',
    'CommonTableExpr.Ctecoltypmods': 'a type or type modifier, filled in by parse analysis',
    'CommonTableExpr.Cterecursive': 'WITH RECURSIVE is WithClause.Recursive, which the builder reads',
    'CommonTableExpr.Cterefcount': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'Constraint.CookedExpr': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'Constraint.Inhcount': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'Constraint.OldConpfeqop': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'Constraint.OldPktableOid': 'an object id, filled in when the statement runs',
    'Constraint.ResetDefaultTblspc': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'CreateSeqStmt.ForIdentity': 'set for the sequence behind an identity column, which PostgreSQL creates itself',
    'CreateSeqStmt.OwnerId': 'an object id, filled in when the statement runs',
    'CreateStmt.Constraints': 'the raw parser puts table constraints in TableElts, which the builder reads',
    'CreateTableAsStmt.IsSelectInto': 'SELECT INTO parses as a SelectStmt with an IntoClause; analysis turns it into CREATE TABLE AS',
    'CurrentOfExpr.Cvarno': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'CurrentOfExpr.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'GroupingFunc.Agglevelsup': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'GroupingFunc.Refs': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'GroupingFunc.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'IndexElem.Indexcolname': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'IndexStmt.Deferrable': 'set for the index behind a PRIMARY KEY / UNIQUE constraint, which the raw parser keeps as a Constraint',
    'IndexStmt.ExcludeOpNames': 'set for the index behind an EXCLUDE constraint, which the raw parser keeps as a Constraint',
    'IndexStmt.Idxcomment': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'IndexStmt.IndexOid': 'an object id, filled in when the statement runs',
    'IndexStmt.Initdeferred': 'set for the index behind a PRIMARY KEY / UNIQUE constraint, which the raw parser keeps as a Constraint',
    'IndexStmt.Isconstraint': 'set for the index behind a PRIMARY KEY / UNIQUE constraint, which the raw parser keeps as a Constraint',
    'IndexStmt.OldCreateSubid': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'IndexStmt.OldFirstRelfilelocatorSubid': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'IndexStmt.OldNumber': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'IndexStmt.Primary': 'set for the index behind a PRIMARY KEY / UNIQUE constraint, which the raw parser keeps as a Constraint',
    'IndexStmt.ResetDefaultTblspc': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'IndexStmt.Transformed': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'IntoClause.ViewQuery': 'filled in by analysis; a materialized view\'s query is CreateTableAsStmt.Query, which the builder reads',
    'JoinExpr.Rtindex': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'JsonBehavior.Coerce': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'JsonFuncExpr.ColumnName': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'JsonParseExpr.Output': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'JsonReturning.Typid': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'JsonReturning.Typmod': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'JsonValueExpr.FormattedExpr': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'MinMaxExpr.Inputcollid': 'a collation, filled in by parse analysis',
    'MinMaxExpr.Minmaxcollid': 'a collation, filled in by parse analysis',
    'MinMaxExpr.Minmaxtype': 'a type or type modifier, filled in by parse analysis',
    'MinMaxExpr.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'NamedArgExpr.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'NullTest.Argisrow': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'NullTest.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'RowExpr.Colnames': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'RowExpr.RowTypeid': 'a type or type modifier, filled in by parse analysis',
    'RowExpr.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'SQLValueFunction.Type': 'a type or type modifier, filled in by parse analysis',
    'SQLValueFunction.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'SubLink.SubLinkId': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'SubLink.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
    'TableLikeClause.RelationOid': 'an object id, filled in when the statement runs',
    'TypeName.TypeOid': 'a type or type modifier, filled in by parse analysis',
    'VacuumRelation.Oid': 'an object id, filled in when the statement runs',
    'XmlExpr.ArgNames': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'XmlExpr.Indent': 'XMLSERIALIZE ... INDENT parses as XmlSerialize, whose Indent the builder reads',
    'XmlExpr.Type': 'a type or type modifier, filled in by parse analysis',
    'XmlExpr.Typmod': 'filled in by parse analysis or when the statement runs; the raw parser never sets it',
    'XmlExpr.Xpr': 'the header of an analyzed expression; empty in a raw parse tree',
};

/**
 * Known bugs: formatting drops these and changes the query's meaning. Fix the builder
 * and printer, add a fixture, and take the entry out.
 */
export const dropped: Record<string, string> = {
    'CTECycleClause.CycleMarkValue': "CYCLE ... SET is_cycle TO 'Y' DEFAULT 'N' loses TO 'Y'",
    'CTECycleClause.CycleMarkDefault': "CYCLE ... SET is_cycle TO 'Y' DEFAULT 'N' loses DEFAULT 'N'",
    'CreateForeignServerStmt.IfNotExists': 'CREATE SERVER IF NOT EXISTS loses IF NOT EXISTS',
    'CreateForeignServerStmt.Servertype': "CREATE SERVER s TYPE 'pg' loses the TYPE",
    'CreateForeignServerStmt.Version': "CREATE SERVER s VERSION '16' loses the VERSION",
    'CreateUserMappingStmt.IfNotExists': 'CREATE USER MAPPING IF NOT EXISTS loses IF NOT EXISTS',
    'CreateTableSpaceStmt.Options': 'CREATE TABLESPACE ... WITH (seq_page_cost = 1) loses the WITH options',
    'DefineStmt.IfNotExists': 'CREATE COLLATION / TYPE / ... IF NOT EXISTS loses IF NOT EXISTS',
    'IndexElem.Opclassopts': 'an operator class\'s parameters, (a gist_trgm_ops (siglen = 32)), are dropped',
};
